JC = javac
JR = java
JFLAGS  = -g -Wall 
 
default: all

all:
	$(JC) *.java

clean: 
	$(RM) *.class

run_server:
	$(JR) Server

run_client:
	$(JR) Client

run_test:
	$(JR) Test

run_test2:
	$(JR) Test2
